name: flutter_base_architecture
description: "Avada Media example Kitty flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  geolocator: ^13.0.2
  http: ^1.2.2

  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # JSON / Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # UI / Routing
  flutter_svg: ^2.2.1
  go_router: ^16.2.4
  smooth_page_indicator: ^1.2.1

  # Auth & Storage
  flutter_secure_storage: ^9.0.0
  jwt_decode: ^0.3.1
  formz: ^0.6.1

  # Optional HTTP client
  chopper: ^8.4.0

  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  shared_preferences: ^2.2.2

  # Payments
  flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_lints: ^6.0.0

  flutter_gen_runner: ^5.7.0


  # ✅ Widgetbook
  widgetbook: ^3.7.0
  widgetbook_annotation: ^3.7.0
  widgetbook_generator: ^3.7.0

  # ✅ Code generation
  build_runner: ^2.4.8
  freezed: ^2.5.4
  json_serializable: ^6.8.0

  # Utils
  rename: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true